version: '3'

services:
  auth:
    build:
      context: .
    ports:
      - '3000:3000'
      - '3001:3001'
  cypress:
    # Using dockerfile instead of image to COPY instead of volumes
    build:
      context: ./e2e
    # image: cypress/included:4.4.0
    depends_on:
      - auth
    environment:
      - CYPRESS_baseUrl=http://auth:3000
