version: "3"

services:
  auth:
    build:
      context: .
    ports:
      - "3000:3000"
      - "3001:3001"
    command: node server/index.js

  shell:
    image: node:12
    ports:
      - "3000:3000"
      - "3001:3001"
    command: /bin/bash
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  cypress:
    # Using dockerfile instead of image to COPY instead of volumes
    build:
      context: ./e2e
    # image: cypress/included:4.4.0
    depends_on:
      - auth
    environment:
      - CYPRESS_baseUrl=http://auth:3000
    # working_dir: /e2e
    # volumes:
    #   - .:/e2e

volumes:
  node_modules:
