version: '3'

services:
  db:
    image: mongo:4.4-bionic
    restart: always
    ports:
      - '27017:27017'
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password

  auth:
    depends_on:
      - db
    build:
      context: .
    ports:
      - '3000:3000'
      - '3001:3001'
    command: node server/index.js
    environment:
      DB_URL: mongodb://db:27017/auth

  test:
    depends_on:
      - db
    image: node:12
    command: /bin/bash -c "yarn && yarn test:db"
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      DB_URL: mongodb://db:27017/auth
  # dev:
  #   image: node:12
  #   ports:
  #     - "3000:3000"
  #     - "3001:3001"
  #   command: /bin/bash
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #     - node_modules:/app/node_modules
  # cypress:
  #   # Using dockerfile instead of image to COPY instead of volumes
  #   build:
  #     context: ./e2e
  #   # image: cypress/included:4.4.0
  #   depends_on:
  #     - auth
  #   environment:
  #     - CYPRESS_baseUrl=http://auth:3000
  #   # working_dir: /e2e
  #   # volumes:
  #   #   - .:/e2e

volumes:
  node_modules:
