version: '3'

services:
  pg:
    image: postgres:13
    restart: always

  # mongo:
  #   image: mongo:4.4-bionic
  #   restart: always
  #   ports:
  #     - '27017:27017'
  #   # environment:
  #   #   MONGO_INITDB_ROOT_USERNAME: root
  #   #   MONGO_INITDB_ROOT_PASSWORD: password

  auth:
    depends_on:
      - mongo
    build:
      context: .
    ports:
      - '3000:3000'
      - '3001:3001'
    command: node server/index.js
    environment:
      MONGO_HOST: mongo

  test:
    depends_on:
      - mongo
    build:
      context: .
    command: yarn test:mongo
    environment:
      MONGO_HOST: mongo
      MONGO_URL: mongodb://mongo:27017/auth
  # dev:
  #   image: node:12
  #   ports:
  #     - "3000:3000"
  #     - "3001:3001"
  #   command: /bin/bash
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #     - node_modules:/app/node_modules
  # cypress:
  #   # Using dockerfile instead of image to COPY instead of volumes
  #   build:
  #     context: ./e2e
  #   # image: cypress/included:4.4.0
  #   depends_on:
  #     - auth
  #   environment:
  #     - CYPRESS_baseUrl=http://auth:3000
  #   # working_dir: /e2e
  #   # volumes:
  #   #   - .:/e2e
  # volumes:
  #   node_modules:
