steps:
  # TODO: Figure out how to pass artifacts across steps
  # - label: 'Install'
  #   command: yarn
  # artifact_paths:
  #   - 'node_modules/**/*'

  - label: ':jest: Jest tests'
    command: yarn --frozen-lockfile && yarn test

  # - wait

  - label: ':cypress: Cypress Tests'
    command: 'yarn cy:run:ci'
    # plugins:
    # - docker-compose#v3.3.0
    # run: auth
    # command: yarn && yarn cy:run
  # depends_on: 'install'
