steps:
  # - label: 'Testing :musical_note:'
  #   command: echo "Hello!"

  # TODO: Figure out how to pass artifacts across steps
  - label: 'Install'
    command: npm install
  #   key: 'install'
  #   artifact_paths:
  #     - 'node_modules/**/*'

  - 'wait'

  - command: '$(npm bin)/cypress version'

  - label: 'Jest tests'
    command: npm test
  # depends_on: 'install'
  # How to use docker?
  # plugins:
  #   - docker#v3.5.0:
  #       image: 'node:12-alpine'
  # - label: 'Start server'
  #   command: |
  #     yarn && yarn start & yarn cypress run
  # - wait
  # - label: 'Cypress Tests'
  #   command: yarn && yarn cypress run
  # depends_on: 'install'
