steps:
  # Currently steps are faster without artifact,
  # leaving this here for reference.

  # - label: 'Install'
  #   command: |
  #     yarn --frozen-lockfile
  #     tar -czf node_modules.tar.gz node_modules
  #   artifact_paths:
  #     - 'node_modules.tar.gz'

  # - wait

  - label: ':eslint: Lint'
    command: yarn && yarn lint
    # command: |
    #   buildkite-agent artifact download node_modules.tar.gz .
    #   tar -xf node_modules.tar.gz node_modules
    #   yarn lint

  - label: ':jest: Jest tests'
    command: yarn && yarn test
    # command: |
    #   buildkite-agent artifact download node_modules.tar.gz .
    #   tar -xf node_modules.tar.gz node_modules
    #   yarn test

  - label: ':cypress: Cypress Tests'
    # command: 'yarn cy:run:ci'
    plugins:
      - docker-compose#v3.3.0:
          run: cypress
