steps:
  - label: 'Testing :musical_note:'
    command: echo "Hello!"

  # TODO: Figure out how to pass artifacts across steps
  # - label: 'Install'
  #   command: yarn
  #   key: 'install'
  #   artifact_paths:
  #     - 'node_modules/**/*'

  - label: 'Jest tests'
    command: yarn && yarn test
    # depends_on: 'install'
    # How to use docker?
    # plugins:
    #   - docker#v3.5.0:
    #       image: 'node:12-alpine'
  - label: 'Start server'
    command: yarn && yarn start

  - wait

  - label: 'Cypress Tests'
    command: yarn && yarn cypress run
    # depends_on: 'install'
